version: '3.8'

services:
  api:
    build: .
    container_name: jbi_api
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]

  worker:
    build: .
    container_name: jbi_worker
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info"]

  redis:
    image: redis:7-alpine
    container_name: jbi_redis
    restart: always
    ports:
      - "6379:6379"
