"""add_ml_task_fields

Revision ID: 6e7f11b512f6
Revises: 9b9f0c57b29e
Create Date: 2026-04-22 01:04:14.239810

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6e7f11b512f6'
down_revision: Union[str, None] = '9b9f0c57b29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('complexity_label', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('task_type', sa.String(length=30), nullable=True))
    op.add_column('tasks', sa.Column('story_points', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('required_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('tasks', sa.Column('risk_factors', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('tasks', sa.Column('subtasks', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('tasks', sa.Column('dependencies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status_changed_at')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'dependencies')
    op.drop_column('tasks', 'subtasks')
    op.drop_column('tasks', 'risk_factors')
    op.drop_column('tasks', 'required_skills')
    op.drop_column('tasks', 'story_points')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'complexity_label')
    # ### end Alembic commands ###
