"""initial_schema

Revision ID: 9b9f0c57b29e
Revises: 
Create Date: 2026-04-14 19:19:53.813809

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b9f0c57b29e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('activity_logs', 'entity_type',
               existing_type=postgresql.ENUM('TASK', 'PROJECT', 'COMMENT', 'MEMBER', 'INTEGRATION', name='activity_entity'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('activity_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_activity_entity', table_name='activity_logs')
    op.drop_index('idx_activity_metadata', table_name='activity_logs', postgresql_using='gin')
    op.drop_index('idx_activity_org_id', table_name='activity_logs')
    op.drop_index('idx_activity_user_id', table_name='activity_logs', postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('ix_activity_logs_organization_id'), 'activity_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.alter_column('ai_predictions', 'model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ai_predictions', 'features_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_ai_predictions_org', table_name='ai_predictions')
    op.drop_index('idx_ai_predictions_task', table_name='ai_predictions')
    op.create_index(op.f('ix_ai_predictions_organization_id'), 'ai_predictions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_predictions_task_id'), 'ai_predictions', ['task_id'], unique=False)
    op.drop_index('idx_analytics_org_id', table_name='analytics_snapshots')
    op.drop_index('idx_analytics_project_time', table_name='analytics_snapshots')
    op.create_index(op.f('ix_analytics_snapshots_organization_id'), 'analytics_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_project_id'), 'analytics_snapshots', ['project_id'], unique=False)
    op.drop_index('idx_comments_org_id', table_name='comments')
    op.drop_index('idx_comments_task_id', table_name='comments')
    op.create_index(op.f('ix_comments_organization_id'), 'comments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.alter_column('github_events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('github_events', 'sha',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('github_events', 'branch',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('github_events', 'author',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_github_events_integration', table_name='github_events')
    op.drop_index('idx_github_events_payload', table_name='github_events', postgresql_using='gin')
    op.drop_index('idx_github_events_type', table_name='github_events')
    op.create_index(op.f('ix_github_events_integration_id'), 'github_events', ['integration_id'], unique=False)
    op.create_index(op.f('ix_github_events_organization_id'), 'github_events', ['organization_id'], unique=False)
    op.alter_column('github_integrations', 'repo_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('github_integrations', 'github_app_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_github_integrations_org', table_name='github_integrations')
    op.drop_index('idx_github_integrations_project', table_name='github_integrations')
    op.create_index(op.f('ix_github_integrations_organization_id'), 'github_integrations', ['organization_id'], unique=False)
    op.alter_column('memberships', 'role',
               existing_type=postgresql.ENUM('OWNER', 'LEADER', 'MEMBER', name='membership_role'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::membership_role"))
    op.drop_index('idx_memberships_org', table_name='memberships')
    op.drop_index('idx_memberships_user_org', table_name='memberships')
    op.drop_constraint('memberships_user_id_organization_id_key', 'memberships', type_='unique')
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'ON_HOLD', 'ARCHIVED', name='project_status'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::project_status"))
    op.drop_index('idx_projects_org_id', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', name='task_status'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::task_status"))
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::task_priority"))
    op.alter_column('tasks', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index('idx_tasks_assigned_to', table_name='tasks', postgresql_where='(assigned_to IS NOT NULL)')
    op.drop_index('idx_tasks_deadline', table_name='tasks', postgresql_where='((deadline IS NOT NULL) AND (is_deleted = false))')
    op.drop_index('idx_tasks_org_id', table_name='tasks')
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_tags', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'google_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'github_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_google_id', table_name='users', postgresql_where='(google_id IS NOT NULL)')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False, postgresql_where='(google_id IS NOT NULL)')
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'github_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'google_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=320),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.create_index('idx_tasks_tags', 'tasks', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_tasks_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_org_id', 'tasks', ['organization_id'], unique=False)
    op.create_index('idx_tasks_deadline', 'tasks', ['deadline'], unique=False, postgresql_where='((deadline IS NOT NULL) AND (is_deleted = false))')
    op.create_index('idx_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False, postgresql_where='(assigned_to IS NOT NULL)')
    op.alter_column('tasks', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::task_priority"))
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', name='task_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::task_status"))
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.create_index('idx_projects_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index('idx_projects_org_id', 'projects', ['organization_id'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'ON_HOLD', 'ARCHIVED', name='project_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::project_status"))
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.alter_column('organizations', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint('memberships_user_id_organization_id_key', 'memberships', ['user_id', 'organization_id'])
    op.create_index('idx_memberships_user_org', 'memberships', ['user_id', 'organization_id'], unique=False)
    op.create_index('idx_memberships_org', 'memberships', ['organization_id'], unique=False)
    op.alter_column('memberships', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('OWNER', 'LEADER', 'MEMBER', name='membership_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::membership_role"))
    op.drop_index(op.f('ix_github_integrations_organization_id'), table_name='github_integrations')
    op.create_index('idx_github_integrations_project', 'github_integrations', ['project_id'], unique=False)
    op.create_index('idx_github_integrations_org', 'github_integrations', ['organization_id'], unique=False)
    op.alter_column('github_integrations', 'github_app_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('github_integrations', 'repo_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_github_events_organization_id'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_integration_id'), table_name='github_events')
    op.create_index('idx_github_events_type', 'github_events', ['event_type'], unique=False)
    op.create_index('idx_github_events_payload', 'github_events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('idx_github_events_integration', 'github_events', ['integration_id'], unique=False)
    op.alter_column('github_events', 'author',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('github_events', 'branch',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('github_events', 'sha',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('github_events', 'event_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_organization_id'), table_name='comments')
    op.create_index('idx_comments_task_id', 'comments', ['task_id'], unique=False)
    op.create_index('idx_comments_org_id', 'comments', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_analytics_snapshots_project_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_organization_id'), table_name='analytics_snapshots')
    op.create_index('idx_analytics_project_time', 'analytics_snapshots', ['project_id', sa.text('recorded_at DESC')], unique=False)
    op.create_index('idx_analytics_org_id', 'analytics_snapshots', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_ai_predictions_task_id'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_organization_id'), table_name='ai_predictions')
    op.create_index('idx_ai_predictions_task', 'ai_predictions', ['task_id'], unique=False)
    op.create_index('idx_ai_predictions_org', 'ai_predictions', ['organization_id'], unique=False)
    op.alter_column('ai_predictions', 'features_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ai_predictions', 'model_version',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_organization_id'), table_name='activity_logs')
    op.create_index('idx_activity_user_id', 'activity_logs', ['user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_activity_org_id', 'activity_logs', ['organization_id'], unique=False)
    op.create_index('idx_activity_metadata', 'activity_logs', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_activity_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('activity_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('activity_logs', 'entity_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('TASK', 'PROJECT', 'COMMENT', 'MEMBER', 'INTEGRATION', name='activity_entity'),
               existing_nullable=False)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
